import Head from 'next/head'
import Image from 'next/image'
import { FormEvent, useContext, useRef } from 'react';
import { AuthContext } from '../contexts/AuthContext';

const Home = () => {
  const { signIn } = useContext(AuthContext);

  const inputEmailRef = useRef<any>(null);
  const inputPasswordRef = useRef<any>(null);

  const formHandler = async (e: FormEvent) => {
    e.preventDefault();

    const data = {
      email: inputEmailRef.current?.value,
      password: inputPasswordRef.current?.value,
    };

    await signIn(data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form onSubmit={formHandler}>
          <input
            ref={inputEmailRef}
            id="email"
            placeholder="Email"
            type="email"
          />

          <input
            ref={inputPasswordRef}
            id="password"
            placeholder="Password"
            type="password"
          />

          <button type="submit">Submit</button>
        </form>
      </main>

      <footer>
        <span >
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </>
  )
}

export default Home;