version: "3.3"

services:
  wp_docker:
    build: .
    container_name: wp_docker
    volumes:
      - ./wp:/usr/share/nginx/html

  wp_docker_nginx:
    container_name: wp_docker_nginx
    image: nginx:1.19.5
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./wp:/usr/share/nginx/html
    links:
      - wp_docker
    depends_on:
      - wp_docker

  wp_docker_mysql:
    container_name: wp_docker_mysql
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wp_docker
      MYSQL_USER: wp_docker_user
      MYSQL_PASSWORD: wp_docker_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
